---
- hosts: testserver
  become: yes
  tasks:
  - name: httpd installation
    yum: 
     name=httpd 
     state=latest
  - name: httpd is running and enabled
    service: 
     name=httpd 
     state=started 
     enabled=yes
